name: quizz_app_maiawad
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - asset/

  fonts:
    - family: Amiri
      fonts:
        - asset: fonts/Amiri-Regular.ttf
        - asset: fonts/Amiri-Italic.ttf
          style: italic
        - asset: fonts/Amiri-Bold.ttf
          weight: 700
    - family: DancingScript
      fonts:
        - asset: fonts/DancingScript-Regular.ttf
    - family: EBGaramond
      fonts:
        - asset: fonts/EBGaramond-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
  
